# run the test suite
tests:
    image: registry.lis-lab.fr:5005/dev/scikit-multimodallearn/ubuntu:22.04
    tags:
        - docker
    script:
        - pip3 install --upgrade setuptools wheel
        - if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
        - pip3 install -e .
        - pip3 install -e .[test]
        - pytest-3
    coverage: '/^TOTAL.+?(\d+\%)$/'
    artifacts:
      paths:
        - htmlcov/

# generate the documentation
doc:
    image: registry.lis-lab.fr:5005/dev/scikit-multimodallearn/ubuntu:22.04
    tags:
        - docker
    only:
        - master
    script:
        - export LC_ALL=$(locale -a | grep en_US)
        - export LANG=$(locale -a | grep en_US)
        - pip3 install --upgrade setuptools wheel packaging
        - if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
        - pip3 install -e .
        - pip3 install -e .[doc]
        - rm -Rf build
        - python3 setup.py build_sphinx
    artifacts:
        paths:
          - public


# project public
#
pages:
    image: registry.lis-lab.fr:5005/dev/scikit-multimodallearn/ubuntu:22.04
    tags:
        - docker
    only:
        - master
    script:
        - export LC_ALL=$(locale -a | grep en_US)
        - export LANG=$(locale -a | grep en_US)
        - pip3 install --upgrade setuptools wheel packaging
        - pip3 install -e .
        - pip3 install -e . [doc]
        - rm -Rf build
        - python3 setup.py build_sphinx
        - cp -r build/sphinx/html public
    artifacts:
        paths:
          - public
